"""initial schema

Revision ID: 278ba38a2efd
Revises:
Create Date: 2026-05-06 11:38:54.256852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278ba38a2efd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_snapshot",
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_per_million_usd", sa.Float(), nullable=False),
        sa.Column("output_per_million_usd", sa.Float(), nullable=False),
        sa.Column("cache_write_per_million_usd", sa.Float(), nullable=True),
        sa.Column("cache_read_per_million_usd", sa.Float(), nullable=True),
        sa.Column("fetched_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("provider", "model"),
    )
    op.create_table(
        "schema_version",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("project", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.create_index("idx_events_project", ["project"], unique=False)
        batch_op.create_index("idx_events_provider_model", ["provider", "model"], unique=False)
        batch_op.create_index(
            "idx_events_request_id",
            ["request_id"],
            unique=True,
            sqlite_where=sa.text("request_id IS NOT NULL"),
        )
        batch_op.create_index("idx_events_timestamp", ["timestamp"], unique=False)

    # ### end Alembic commands ###

    # Seed the spec's schema_version table. Alembic tracks per-revision state
    # in `alembic_version`; this row is the user-facing "schema major" the spec
    # documents and that tooling can read without depending on Alembic.
    op.execute(sa.text("INSERT INTO schema_version (version) VALUES (1)"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.drop_index("idx_events_timestamp")
        batch_op.drop_index("idx_events_request_id", sqlite_where=sa.text("request_id IS NOT NULL"))
        batch_op.drop_index("idx_events_provider_model")
        batch_op.drop_index("idx_events_project")

    op.drop_table("usage_events")
    op.drop_table("schema_version")
    op.drop_table("pricing_snapshot")
    # ### end Alembic commands ###
